"""add sketch columns to designs

Revision ID: d50118650e0c
Revises: ca3c9a98b59e
Create Date: 2026-09-08 14:51:53.755034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd50118650e0c'
down_revision: Union[str, None] = 'ca3c9a98b59e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('designs', sa.Column('sketch_key', sa.String(length=500), nullable=True))
    op.add_column('designs', sa.Column('sketch_content_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('designs', 'sketch_content_type')
    op.drop_column('designs', 'sketch_key')
    # ### end Alembic commands ###